### Create a new song.
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Love Me",
  "releasedDate": "2020-01-01",
  "duration": "2:30",
  "lyrics": "lyrics"
}

### Get all songs.
GET http://localhost:3000/songs

### Get song by ID.
GET http://localhost:3000/songs/68dbf959f8d16b235239ae7f

### Delete song by ID.
DELETE http://localhost:3000/songs/68dc0d8f0ce7122e0a06ee0a

### Update song by ID.
PUT http://localhost:3000/songs/68dc0d8f0ce7122e0a06ee0a
Content-Type: application/json

{
  "title": "Love Me",
  "releasedDate": "2061-01-01",
  "duration": "2:30",
  "lyrics": "lyrics"
}

### Create album.
POST http://localhost:3000/albums
Content-Type: application/json
