### Create a new song.
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Love Me",
  "releasedDate": "2020-01-01",
  "duration": "2:30",
  "lyrics": "lyrics"
}

### Get all songs.
GET http://localhost:3000/songs

### Get song by ID.
GET http://localhost:3000/songs/68dbf959f8d16b235239ae7f
