### Get Hello World
GET http://localhost:3000/

### Create New Song
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3NTg3MjQxNDYsImV4cCI6MTc1ODgxMDU0Nn0.3y9sjDxwkhFGSi2hkLC4C0CurW0qLNndYMiUELWyE4s

{
  "title": "Animals",
  "artists": [1],
  "releasedDate": "2023-09-29",
  "duration": "02:34",
  "lyrics": "I'm your last lover."
}

### Get All Songs
GET http://localhost:3000/songs?page=1&limit=2

### Get One Song by ID
GET http://localhost:3000/songs/2

### Update Song by ID
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
  "title": "You for me",
  "artists": [1, 3],
  "releasedDate": "2023-05-11",
  "duration": "02:34",
  "lyrics": "I'm your last lover."
}

### Delete Song by ID
DELETE http://localhost:3000/songs/1

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "password": "12345"
}

### Signup Artist
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Martin",
  "lastName": "Garrix",
  "email": "martin@gmail.com",
  "password": "12345"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "12345"
}

### Login Artist
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "martin@gmail.com",
  "password": "12345"
}

### Get Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc1ODcwNjI1OCwiZXhwIjoxNzU4NzkyNjU4fQ.0-wA5w11OtNrLiAIMdx7SFl5SZnrAYC8WJo-aY29HU8

### Get Artist Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTc1ODcyMjcyMSwiZXhwIjoxNzU4ODA5MTIxfQ.wPgDzlMHanhuNZwVfJqoyJankOA2Y_WA3CGOvjkYfzA

### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3NTg4MTg5MDQsImV4cCI6MTc1ODkwNTMwNH0.OLu8J_F5jrhoF-MgiDgAvhrscOh0XXLdFe0Oc3RoDlA

### Validate 2FA Token
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3NTg4MTg5MDQsImV4cCI6MTc1ODkwNTMwNH0.OLu8J_F5jrhoF-MgiDgAvhrscOh0XXLdFe0Oc3RoDlA
Content-Type: application/json

{
  "token": "937683"
}

### Disable 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbkBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3NTg4MTg5MDQsImV4cCI6MTc1ODkwNTMwNH0.OLu8J_F5jrhoF-MgiDgAvhrscOh0XXLdFe0Oc3RoDlA

### Access Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer e807f506-fca9-45a7-a5d7-cd4cc692b747
